spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:src/main/resources/data.db"

#D:/SQLiteStudio/Database/data.db

FileSystem:
  chatNodeSavePath: "D:\\SQLiteStudio\\Database\\"
#Http:
  #download_path: "D:\\"